#!/bin/bash
#
# Used by Travis to submit named assets to the correct environments.

set -euo pipefail

BRANCH="$(git symbolic-ref -q HEAD || echo "pr")"

case ${BRANCH} in
  refs/heads/master)
    echo "Submitting to production."
    export CONTENT_STORE_URL=https://developer.rackspace.com:9000/
    export CONTENT_STORE_APIKEY=${PROD1}${PROD2}${PROD3}
    ;;
  refs/heads/redesign)
    echo "Submitting to staging."
    export CONTENT_STORE_URL=http://staging.developer.rackspace.com:8000/
    export CONTENT_STORE_APIKEY=${STAGE1}${STAGE2}${STAGE3}
    ;;
  *)
    echo "Not submitting anywhere."
    ;;
esac

npm install
grunt build
